name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AureaAurum/PtN_tool
          depth: 1
          path: ptn-tool
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            !public/*
            /*
          sparse-checkout-cone-mode: false # required for ! entry to work
      - name: copy
        run: cp ptn-tool/* copy
      - name: Clean ptn-tool
        run: rm -rf ptn-tool
      # プルリク作成
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'Update Assets'
          branch: feature/asset-files-changes
          base: master
          # 同一ブランチ名にならないよう後ろにタイムスタンプを付加
          branch-suffix: timestamp
          delete-branch: true
