name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AureaAurum/PtN_tool
          depth: 1
          path: ptn-tool
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            !public/*
            /*
          sparse-checkout-cone-mode: false # required for ! entry to work
      - name: copy
        run: cp -RT ptn-tool copy
      - name: Clean ptn-tool
        run: rm -rf ptn-tool
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          push-to-fork: machine-user/fork-of-repository
