name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - name: Clone another repository
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/AureaAurum/PtN_tool
