name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Aurea_Aurum/PtN_tool
          sparse-checkout: |
            !public/*
            /*
          sparse-checkout-cone-mode: false # required for ! entry to work
