name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          repository: AureaAurum/PtN_tool
          path: ptn-tool
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            !public/*
            !.git/*
            /*
          sparse-checkout-cone-mode: false # required for ! entry to work
      - name: copy repo　
        env:
         SECRET_TOKEN: ${{ secrets.ACCESSTOKEN }}
        run: |
           cp -RT ptn-tool main
           cd main
           pwd
           ls -la
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add .
           git commit -m "Copy files from external repository"
           git remote add neworigin https://${GITHUB_ACTOR}:${SECRET_TOKEN}@github.com/AureaAurum/PtN_tool_code
           git push -f neworigin main
