name: git sparse-checkout (exclude)
on:
   workflow_dispatch:
jobs:
  sparse-checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AureaAurum/PtN_tool
          depth: 1
          path: ./ptn-tool
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            !public/*
            /*
          sparse-checkout-cone-mode: false # required for ! entry to work
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            commit-message: 'copy test'
            branch: copy_target
            branch-suffix: timestamp
            delete-branch: true
            title: 'updated target.yml'
